name: Gerar APK AnimeFlix

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências do backend
        working-directory: backend
        run: npm install

      - name: Executar seed do backend
        working-directory: backend
        run: npm run seed

      - name: Instalar dependências do app
        run: npm install

      - name: Gerar versão web
        run: npm run build

      - name: Criar projeto Android com Capacitor
        run: npx cap add android

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gerar APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Publicar APK
        uses: actions/upload-artifact@v4
        with:
          name: AnimeFlix-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
